### ISSUE TITLE
Failed to open TCP connection to api.github.com:443

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-cli-build#1]
https://travis-ci.org/lightbend/reactive-cli-build/builds/399884404

```
Deploying application
/Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known) (Faraday::ConnectionFailed)
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /Users/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/client/releases.rb:32:in `create_release'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-releases-1.9.7/lib/dpl/provider/releases.rb:106:in `push_app'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/lib/dpl/provider.rb:195:in `block in deploy'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/lib/dpl/cli.rb:41:in `fold'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/lib/dpl/provider.rb:195:in `deploy'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.9.7/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/dpl:23:in `<main>'
failed to deploy
/Users/travis/.travis/job_stages: line 78: shell_session_update: command not found
```

**Comment by eed3si9n** [comment]
Rerunning the job seems to have worked.
